### PR TITLE
improve to Authentication schema. solving error using ZK without Auth. 

### PR DESCRIPTION
**Pull request by eraigosa**
small changes. My IDE changes automatically the indentation, sorry about that.

### CODE REVIEW

**Comment by fglaeser** [comment]
I've added an .editorconfig to fix the indentation problem. Could you fix the indentation of your PR and sent it again?
Thanks.

**Review by fglaeser — CHANGES_REQUESTED** [review]
Fix indentation.

**Comment by eraigosa** [comment]
hi, are you sure the CI is working ok? I didn't change anything that can affect it (at least I think)

**Comment by fglaeser** [comment]
One test is failing, did you run the test locally?

**Comment by eraigosa** [comment]
no, because I don't have your same configuration in My ZK, I executed my own test (in my app) and it worked.

**Comment by fglaeser** [comment]
You only need a ZK running at localhost:2181. Tell me if you are not able to run the test. Thanks

**Comment by eraigosa** [comment]
I ran my own test (in my app) and it worked... 
I didn't have your same configuration... so I installed ZK in my machine and when I ran the test I got this error... 
image

but in the previous push, it didn't report any error... 
it is done, I modified the test now

**Review by fglaeser — APPROVED** [review]

**Pull request merged**
